### ISSUE TITLE
Crash when generating burned tree

### ISSUE THREAD

**Issue by zEpiixz** [MysticMods/MysticalWorld#112]
https://paste.dimdev.org/unacaquseh.mccrash

**Comment by noobanidus** [comment]
I've seen this crash before, let me dig through the old issues...

**Comment by noobanidus** [comment]
Yeah, please see #54 and #51. The last time this issue was raised I couldn't find any possible solution; it doesn't make sense to me that the "world" object of a generator (which is provided by Minecraft) could possibly be null.

It has to be an interaction with another mod, but I don't really know how to work it out.
