### ISSUE TITLE
Gold Dust does not have a smelting recipe associated with it.

### ISSUE THREAD

**Issue by Birgliss** [MysticMods/MysticalWorld#164]
We're currently not generating a recipe for gold dust (and possibly iron dust/mod-specific dusts, haven't tested) to be smelted/blasted into ingots.
At first glance this seems to be a non-issue, as we don't add a way to obtain gold dust in this mod yet.
Some mods (like Futurepack) default to other mods' dusts by default, however, [as seen here in the Mystic Mods discord.](https://discordapp.com/channels/455383608773836801/639247677032366100/709073495015030864)
In this case, we want to generate a smelting recipe, potentially for all of the dusts, even if they're not "enabled."

**Mystic Mods Versions**

- MysticalLib: 1.16.1
- MysticalWorld: 1.9.3

**Other Versions:**
- Forge: 28.2.11
- Minecraft: 1.14.4

**Comment by noobanidus** [comment]
That's really strang ebecause I swear I actually fixed this.l.. I'll take another look into it.

**Comment by Divineaspect** [comment]
Same for Iron dust.

**Comment by Divineaspect** [comment]
And pretty much every other metal

**Comment by noobanidus** [comment]
Well, this certainly isn't the case for the latest release of Mystical World -- iron and gold dusts were missed, but I'm looking in the generated resources folder and I see "copper_ingot_from_smelting_dust", etc. 

Iron and gold were missed purely because the block <-> ingot <-> nugget recipes were abstracted out and I moved the dust into those, and as we don't control iron blocks or nuggets, etc, they somehow got lost in the conversion to Registrate.
