### ISSUE TITLE
Disabled "Smooth Lighting" causes black outlines for thatch blocks

### ISSUE THREAD

**Issue by MangoPicante** [MysticMods/MysticalWorld#20]
With "smooth lighting" off, the thatch texture appears bugged. The main thatch block texture appears as intended, but the extensions are black.

**Comment by Davoleo** [comment]
yeah, this lighting bug has been a thing since the first testing builds :P

**Comment by TheSexyYeti** [comment]
Yeah I noticed it too when I had roots 3 installed in my mod pack. Is there any easy way to fix this. Because I hate not to have this mod in my pack.
![2019-08-02_20 17 30](https://user-images.githubusercontent.com/50222286/62404522-dcf55980-b562-11e9-96d8-f049c1fdd46f.png)

**Comment by MangoPicante** [comment]
The quick and dirty fix is to bump up smooth lighting to the absolute minimum and it looks fine. Haven't found any other way to fix it on our non developer end. @TheSexyYeti

**Comment by duely** [comment]
And on the developer end, I honestly have no idea why this is happening. It could be a side effect of the model, in that those quads are considered outside of the model space and therefor not actually "lit", as I noticed in a screenshot someone took to demonstrate an issue with the Root's Wildwood leaves that their Grove Stone was almost completely black.

Unfortunately, I don't really know enough about models or modeling to be able to comprehend it. I took a dive back through the source code but I can't find a version since the final release of Roots 2 (where thatch existed) until now where it works properly with the lowest setting.
