### ISSUE TITLE
multiple issues with most recent update

### ISSUE THREAD

**Issue by AceCardDraws** [MysticMods/MysticalWorld#205]
I don't know how to program code well, but these are some issues I noticed, once silver foxes are tamed, front legs stay permanently in a sleeping position, and the tail is curled under legs, this happens so all newly spawned foxes from that point on; along with them floating if told to lay down. Lava cats once tamed are frozen in place unable to move from the taming position. beetles can not be placed on the shoulder after being tamed. Like I said at the start these are the notable issues I saw at the start and require me to fully delete the mod and reinstall for me to fix it. I hope this helps and I wish you luck.

**Comment by noobanidus** [comment]
> beetles can not be placed on the shoulder after being tamed.

This wasn't implemented in later versions (1.15 onwards) due to code changes.

> once silver foxes are tamed, front legs stay permanently in a sleeping position, and the tail is curled under legs

I had thought this was fixed, but thanks for pointing it out. It looks like the model is never being reset after the initial sitting-position is applied.

> and require me to fully delete the mod

So long as you have no sitting entities you shouldn't need to delete the mod and reinstall. Simply restarting the game should be sufficient.

**Comment by noobanidus** [comment]
Most of these should be fixed. Sitting is another issue entirely -- for some reason.
