### ISSUE TITLE
Please read highlighted comment if you have too many Hell Sprouts!

### ISSUE THREAD

**Issue by NickKnax** [MysticMods/MysticalWorld#226]
Hi! For whatever reason in the nether, hell sprouts spawn an insane amount and don’t despawn. It may be an outdated version (I am playing through CurseForge’s Valhesia 3 modpack) but it got to the point that I couldn’t move and had to use the /kill hell sprout command which killed almost 6000 of them. Just wanted to let you know about this!

**Comment by noobanidus** [comment]
Do you have any screenshots or a copy of the save file?

**Comment by Sebaz00** [comment]
http://prntscr.com/wlhzig

I have the exact same issue on the same modpack. It seems to only be the case in the warped fungal biome. They seem to not abide by the spawn limit and just keep spawning. If this has been fixed already lmk and I'll see if I can get notify the valhesia 3 devs to update their modpack.

**Comment by Oriaxx** [comment]
I'm having the same problem except i'm playing in all the mods 3 remix
https://imgur.com/a/EdRmeee

**Comment by noobanidus** [comment]
Yeah, I'm going to need to convert to some sort of sampling system to determine the weight of hell spawns as other creatures seem to crowd it out in some biomes, but then don't in others.

**Comment by noobanidus** [comment]
@NickKnax @Sebaz00 @Oriaxx Is there any chance you could tell me what the "chance" value is set for the hell sprouts in your configuration? I'm wondering if an old version shipped out and the update I made to the default hasn't been overwritten.

**Comment by Sebaz00** [comment]
It's at 100 for me. http://prntscr.com/x6r0lj

**Comment by Oriaxx** [comment]
https://imgur.com/a/fnYVRtc

**Comment by NickKnax** [comment]
From what I’ve seen in the Valhesia 3 modpack, it looks to be fine in it now, I guess they updated it!

**Comment by noobanidus** [comment]
@Sebaz00 Ah, that's the grow chance. It looks like the config for spawn chance has been updated to 8; I'd recommend reducing this value if you still have issues, otherwise I might need to create per-biome spawn chance injection.

If anyone else is having issues still with the latest release and the spawn chance set to 8, try reducing it and try reducing the max group size to 1 or 2. If that still doesn't solve it, please comment on this issue.

**Comment by Tsuyurin** [comment]
I had/have the issue in Valhelsia 3 as well. Was going to build an Enderman farm far above the nether roof at Y=200+ over a warped forest, but at around 3000 Hell Sprouts my game had ground to a halt with less than 1 fps. Once I noticed that was the problem and killed them off with commands, I took a look at the entity counter, and they were accumulating at a rapid rate whenever I was up there.

Reducing spawn chance & group size seems like it will only slow this down, not stop them from eventually clogging the game. The question I wonder is why they completely ignored the passive mob cap to accumulate in such ludicrous quantities.

**Comment by noobanidus** [comment]
Ah, now this may be the core issue, thanks for that extra bit of info, @Tsuyurin. I'll need to triple check if they're indeed being added in as creatures rather than monsters; in previous versions, an entity classified as a creature would never actually spawn, thus they had to be done as monsters. I'll try to look into this tomorrow.

**Comment by noobanidus** [comment]
e4838cb3b37 may resolve the issue but I'll need to test it a little more extensively.

**Comment by Pelotrio** [comment]
@noobanidus Multiple people also reported this issue for atm3 remix and that's why I looked into it.  Shouldn't all mobs be still capped by the mob cap? I mean you can change the classification of that mob and you can reduce the spawn rates but if it would all be solved if they would not disregard the cap. I am not too sure how Minecraft handles the cap internally but normally there should not even be more then 70 if they are classified as a monster. That's just my thoughts correct me if I am wrong as I am not sure about the technical details.

**Comment by noobanidus** [comment]
@Pelotrio Modders don't generally have any way of affecting whether or not a mob is affected by the mob cap or not. There's two possible factors here, most likely:

a) The fact is that the "shouldDespawn" function is set to false (i.e., as how most passive creatures are handled) but being generated in the monster category means that additional creatures are being spawned and previous creatures never despawn.
b) Combined with chunk handling means that monster entities that *should* despawn not despawn. Generally this also has to do with entities wandering off into unloaded chunks.

I'm not 100% on the details but this has been my experience with previous similar situations.

**Comment by Clarencerainsford** [comment]
Hey there. It said beetles could ride on your shoulder if you sneak-right click, but it just doesn't happen for me. It just treats it like a normal right-click where the beetles change from standing to sitting.

**Comment by noobanidus** [comment]
Has anyone experienced this in 1.16 since e4838cb?

**Comment by noobanidus** [comment]
Given that there have been no relevant reports since I changed in e4838cb, which was over a month ago (and there's been time for it to filter through to various modpacks), I'm going to assume the 1.16 issue has been resolved. I see that there's an issue linking back which is related to 1.12, but unfortunately I'm not sure what to do about that one.
