### ISSUE TITLE
[1.16.5] Complexify stuffed aubergine recipe

### ISSUE THREAD

**Issue by ArchieBeepBoop** [MysticMods/MysticalWorld#242]
**Describe your suggestion:**
Realizing that stuffed aubergines can be made with other aubergines kind of makes the point of making any other food sorta moot. This makes them really easy to make by farming a single material.

Perhaps we could make it so it cannot be crafted with other Aubergines, at least?

**Describe alternatives you've considered:**
No alternatives.

**Additional context:**
No context.

**Comment by noobanidus** [comment]
It's possible but it makes compatibility somewhat frustrating. 

Currently, there are currently the following ingredients:

- Cooked aubergine
- Vegetable tag
- Vegetable tag
- Cooked vegetable tag

I could create "vegetable_without_aubergine", and "cooked_vegetable_without_aubergine" tags but I couldn't automatically fill them up in the same way that the vegetables tags are (thus meaning pack makers would have to modify them for compatibility) because other mods are just adding to the pseudo-standard "forge:vegetables" tag. 

I'm not sure if there's a way to generate a tag that is a subset of another tag but it would be next to impossible to know for certain what is an aubergine or not (say if the mod called the item "purple_thing" everywhere, didn't tag it as an aubergine, tagged it as a vegetable, and only use the translation to call it "aubergine" -- which would prevent the server from knowing it as there are no translations on the server, so the recipe sync would treat it like any other vegetable). Not to mention eggplant.

On a recipe-level, I think one of the things I can do is, as I'm controlling the cooked vegetables tag, is to exclude the second cooked vegetable from being aubergine (I'll need to triple-check exactly how I'm doing it). Alternately, I might be able to make it into a special recipes that checks that "cooked aubergine doesn't match cooked vegetable" and that "uncooked vegetable doesn't match other uncooked vegetable".

Sorry for the waffle! My brain kinda got ahead of me there.
