### ISSUE TITLE
[1.16.5] Option to deactivate the complete ore material

### ISSUE THREAD

**Issue by lublak** [MysticMods/MysticalWorld#251]
**Describe your suggestion:**
Currently MysticalWorld adds a bunch of ores and "vanilla likes" tools for it.
I want to disable everything because it is duplicated with other mods.
And some are unnecessary.

**Describe alternatives you've considered:**
Currently two options:
- remove the mod from the list
- clear dimensions = [] and disable all items with crafttweaker (rather unattractive)

**Comment by noobanidus** [comment]
You can also disable the ores by setting the spawn chance/count per chunk to 0, they should no longer spawn. This should be indicated in the configuration comment.

However, I have no intention of doing any sort of conditional registration. You're welcome to disable the recipes and use JEITweaker to hide them from JEI, but I have absolutely *no* intention of making it so that you can completely remove things from mods entirely from registration.
