### ISSUE TITLE
Incompatibility with Underground Biomes mod

### ISSUE THREAD

**Issue by Zygus42** [MysticMods/MysticalWorld#40]
MysticWorld-1.12.2-1.4.3
UndergroundBiomesConstructs-1.12-1.3.7

All ores from this mod look like this in the world and JEI:
![2019-08-30_15 08 49](https://user-images.githubusercontent.com/20757445/64000478-6a16d880-cb38-11e9-8c3b-bc72f1153ea7.png)

This happens even if you turn the world gen from this mod off, due to the odd way that Underground Biomes defines it's ore blocks.

The real irony of it is that I don't even want this mod, I just wanted to use the Roots mod, but that needs this as a dependency.

**Comment by Mrthomas20121** [comment]
first of all, MysticWorld is used by roots because it need it. just like thermal expansion require cofh world.
if it doesn't work, it's probably my fault since i did a pr to underground biomes to add supports for Astral Sorcery and Mystic World. will look into it to see what is the problem. but from what i see, they have no overlays which cause the block to show the missing texture.

**Comment by Mrthomas20121** [comment]
in the meantime to fix it you can use this file https://gist.githubusercontent.com/Mrthomas20121/038335478c145c09666c1dd28bf0a511/raw/4801cd399afc451cecbbbabae245b2a880973061/mysticworld.json. put it in config/undergroundbiomes/ores/

**Comment by duely** [comment]
Consider Mystical World a library mod "with content". As @Mrthomas20121 said, it is required for roots as it provides a number of features, including Sprouts (though these may move to Roots at some point in time). 

This ticket needs to be opened on the Underground Biomes tracker. We are not providing any of the compatibility they are using, and as far as I'm aware the mod works without issue in a normal world (without this mod installed). There is literally nothing that I can do to help with your issue.
