### ISSUE TITLE
Many huts and barrows spawning near each other

### ISSUE THREAD

**Issue by turabian-luvr** [MysticMods/MysticalWorld#41]
The attached screenshot shows 3 barrows and 5 druid huts spawned next to each other in a new single player world.

In mysticalworld.cfg, both I:BarrowDistance and I:HutDistance are set to 600.

![2019-08-31_16 12 53](https://user-images.githubusercontent.com/54744184/64065913-a1a28500-cc0b-11e9-8308-c80a98bdb54e.png)

**Comment by duely** [comment]
This is unfortunately a side effect of the system: as chunks can be generated at the same time, each chunk believes (until it is complete) that it is more than 600 from another structure. It's something that you may notice with other mods, such as Astral Sorcery.

There is perhaps the possibility of using rarity-based spawning instead of distance based spawning (or perhaps in addition), but again that has the chance to have the confluence of RNG such that multiple structures spawn in the same area, while at the same time making it difficult for some structures (such as barrows) to actually spawn given their space requirements.

In addition, the loot of these structures is being re-balanced in a future update.

I'm going to leave this issue open as a reference point for future work on world generation & structure placement, as well as a "known issue".
