### ISSUE TITLE
the owl entity is crashing my game

### ISSUE THREAD

**Issue by DarkNight0926** [MysticMods/MysticalWorld#43]

**Comment by duely** [comment]
If that is the case, please provide a crash report as well as a list of other mods installed.

**Comment by Ilysen** [comment]
I'm unsure how much I can help here, but I'm having the same issue. It seems to be a crash specific to version `1.4.4`, as downgrading to `1.4.3` fixed the problem for me.

I have very few mods loaded - JEI, Mystical Lib, Mystical World, Patchouli, and Roots.
![image](https://user-images.githubusercontent.com/47678781/64897855-e6d6a600-d652-11e9-934a-b38b80ced46b.png)

I had the issue on the Forge verison of 14.23.5.2847. Here's the full crash log:
[crash-2019-09-13_18.15.58-client.txt](https://github.com/MysticMods/MysticalWorld/files/3611963/crash-2019-09-13_18.15.58-client.txt)

Not sure if I can do anything to help otherwise, but I hope this sheds some light.

**Comment by duely** [comment]
That's... super-strange. I'm going to check the upload of 1.4.4 to make sure it wasn't somehow corrupted. Thank you so much for the further information, this actually allows me to start investigating it!

**Comment by duely** [comment]
Okay, so digging into the actual `.jar` that's available on CurseForge, the EntityOwl definitely exists, and the point at which this error is occurring (`initializedMods`) is late enough in the process that Mystical World should have already loaded... I'll dig even deeper.

**Comment by duely** [comment]
So, I'm not able to replicate this. The only thing I can recommend doing at this point is deleting 1.4.3 and reinstalling 1.4.4, as potentially it was a corrupted or invalid mod file. It doesn't seem to be happening any more, but I've had a number of issues where files that I've uploaded, even though they've been stated as the correct size, are being reported as identical to an "empty file"...
