### ISSUE TITLE
Flower-based soups and salads

### ISSUE THREAD

**Issue by noobanidus** [MysticMods/MysticalWorld#47]

**Comment by majijn** [comment]
i was actually gonna suggest something like this so i had already had a couple of example dishes thought out 

pereskia stew: pereskia bulb, allium, carrot, (herb that can be used for spicing), flour.
petal salad: allium, rose bush/poppy , dandelion , 
rose delight: flour, roasted pereskia, sugarx2 , rose bush/petals ( yes a turkish delight but idk what it would want to be named in game)
sunflower seeds/sunflower butter would also be nice

**Comment by GentlemanGnu** [comment]
Lets start here.... https://orchidrepublic.com/blogs/news/are-orchids-edible
which crosses off.... Blue Orchid, Roses (hips dried as teas/desserts, petals in salads and drinks), Peonies, Sunflowers (petals, seeds and roots can be eaten)

Dandelion	-https://www.abc.net.au/news/health/2016-05-12/edible-weeds-and-how-you-can-use-them/7406004  
Got some dandelions, for example? The yellow petals and young leaves can be used in salads, and the roots can be used as a coffee substitute   

Poppy	- https://www.thompson-morgan.com/edible-flowers
Californian Poppy	Eschscholtzia	Fresh or dried leaves can be used to make a herbal tea which is known to be soothing and relaxing.
but also... All poppies are poisonous. However the seeds produced from Papaver somniferum and Papaver paeoniflorum can be eaten. The seeds of other species are not edible.

Allium - https://homeguides.sfgate.com/alliums-edible-91526.html 
The diverse genus Allium contains approximately 800 species, although only a few of these are familiar as food crops -- mainly onions (Allium cepa), garlic (Allium sativum), leeks (Allium ampeloprasum) and chives (Allium schoenoprasumand). These Allium have been cultivated for centuries, and used to add flavor and zest to food. Many more species are grown for their ornamental value, but even these are theoretically edible, although not likely as tasty as food crop species.  

Azure Bluet 	- http://thebotanicalhiker.blogspot.com/2015/04/eating-wild-identifying-wild-edible.html
Look for Bluets amongst grassy areas, such as meadows, lawns, grassy trails, or amongst tufts of grass at the bases of trees. I tend to use these like sprouts, and it is easy to harvest a clump of them, given that they will often grow in mats or at least abundance. All above grounds parts are edible. Simply grab a handful and with a sharp knife, slice at base of stems. They are best added raw to salads or sandwiches, as they will not hold up to cooking.

Tulips 	- http://alloveralbany.com/archive/2008/05/09/tulips-really-are-edible-sort-of
There seems to be pretty wide consensus that the petals of tulips are OK to eat. They reportedly range in taste from "a mild bean-like taste, to a lettuce-like taste, to no taste at all." There are a bunch of recipes that use tulip petals: as cups for mousse, accents for tuna, for salad dressing, and little dishes for appetizers. We even turned up a recipe for tulip wine, which is apparently "a lovely white".


Oxeye Daisy 	-https://www.wildflowers-and-weeds.com/weedsinfo/Chrysanthemum_leucanthemum.htm
used in salads, battered, pickled as flowers and leaves... as well as medicinally.

Lilac	-https://www.thepracticalherbalist.com/holistic-living/lilac-an-edible-and-medicinal-treat/
The flowers are edible and have some medicinal qualities. I have to say eating even a single flower raw is a flavor exploding experience with slight astringency (drying to tissues), almost bitter, and very floral. I would say these are best for garnishes and edible flower displays on pastries rather than whole meals.







CornFlower 	-  https://en.wikipedia.org/wiki/Centaurea_cyanus
The edible flower of the cornflower can be used for culinary decoration, for example to add colour to salads. Cornflowers have been used historically for their blue pigment. Cornflowers are often used as an ingredient in some tea blends and herbal teas.
Cornflower seed is one of the favourite foods of the European goldfinch.

Wither Rose - Seems to be a Minecraft Specific thing... Despite being a "rose"  I would not put this in food

Lily of the Valley - hard NO.... very poisonous  Pretty, but they contain convallatoxin, which should not be ingested https://www.thompson-morgan.com/edible-flowers

**Comment by duely** [comment]
This is mainly waiting on 1.14 appropriate textures, and will most likely not make it into 1.12.
