### ISSUE TITLE
Requested pastebin related to "WorldGenBurntTree" Crash.

### ISSUE THREAD

**Issue by XvBUSHvX** [MysticMods/MysticalWorld#54]
as requested in #51. The crash log.
https://pastebin.com/J5p5NquS

If there is any other information I could provide to you, feel free to let me know.

**Comment by duely** [comment]
Aweomse, thanks; does this crash occur without dynamic trees installed?

**Comment by XvBUSHvX** [comment]
I have only been able to experience it once. In fact I only have a suspicion of what "worldgenburnttree" even is. Prior to the crash I had discovered a large (very large) tree that followed the vanilla generation rules. The crash happened after I had already left the chunks it was located in IF that was the cause. 

I only found this project site and the other thread by searching the terms from the crash report. 

Quote from the other thread - 

> In the process of making this post I disabled the second set of mods and just flew around the map (something that typically makes my toast cry).
> 
> The lag spikes and relating errors I was receiving was greatly reduced.
> 
> As I am not sure what caused my crash, which incidentally was bad enough to completely close the MultiMC launcher, I wasn't able to attempt to recreate the crash. Thus am not aware if the crash was caused by the second group of mods, but am certain that the lag spikes are related.

I will continue testing and attempting to see if I can recreate it, will likely take me a day or two, but I will post again as I find more information.

**Comment by XvBUSHvX** [comment]
Ok, so the burnt tree is the one that spawns of "charred_log" isn't it?

**Comment by duely** [comment]
The burn tree is the one on the left in [this image on reddit](https://old.reddit.com/r/feedthebeast/comments/d7zi9z/i_play_modded_for_views_like_these/). 

The crash here is specifically that the generator for the burnt tree, which is registered like any other generator and uses the same logic & functionality as a vanilla tree is, for some reason, reaching a certain point where it's reference to the "world" currently being generated in has become null for some reason.

I'm curious if this is caused by Dynamic Trees in your case, or if it is a common/shared mod with the other poster. The fact that they were updating from a pre-existing world made me suspicious that there might be issues, hence wanting to know if:

a) They could reproduce the crash in a fresh new world outside of their currently existing one?
b) Whether the crash happened at the same location in their existing world or if they could repeatedly trigger the crash in a discernible way?

Given that I've never had an error like this occur in any world, so I don't really have an indication as to what's causing it (and the crash log unfortunately tells me nothing), I'd like to ask you basically the same questions:

a) Can you reproduce the crash without Dynamic Trees installed? I know that there are specific instances where certain generators can crash/that there are incompatibilities between Dynamic Trees and other mods which install trees.
b) Does it happen with any other tree generators, such as those from Rustic?
c) Does it consistently happen in a fresh new world in a way that you can reproduce?

**Comment by raltus** [comment]
I found a couple cascades in the game logs after another crash. I've added the files to mine.

**Comment by XvBUSHvX** [comment]
That was the tree I found. I found it by traveling in the direction I was headed when the crash occurred. And though not actually measured, it did appear to be near render distance from where I crashed. 
I will continue testing to see if and how I can recreate it. 

The world the initial crash happened in was a new world. I just began working on modifying the RLCraft pack and was looking around to see how well it would run with the new mods. 

I disabled the second set of mods before loading back into the world, however I think that once it happens I will have to continue loading chunks until the 'burnt tree' attempts to load again.

I have a few suspicions on would could be causing it and will work towards recreating it.

**Comment by XvBUSHvX** [comment]
I don't think this can be consistently and reliably recreated. 

I took it back to the same conditions I experienced the first crash in. I went flying around again. And though I was experiencing a great deal of lag and some really bizarre log messages. I was able to find the burnt tree multiple times. 

This may be an odd mix of factors.

I'm only working on a pack for a couple of friends on a small private server so I'll keep it installed and monitor it and see if we cause it to happen again. If so hopefully I will be able to see a pattern. If you'd like close this for now and if I do find anything out I will post in here again.
