### ISSUE TITLE
Add aubergine seed drop rate config

### ISSUE THREAD

**Issue by nickjackson-ff** [MysticMods/MysticalWorld#55]
It would be great to have control over how often aubergine seeds drop from grass, if at all.

**Comment by duely** [comment]
While a part of me would like to say "that's easily doable", and it is, aubergines are an intrinsic part of the mod, and an intrinsic part of Roots, which depends on them. I'm not comfortable with making an essential part of the mod "optional" as it were via configuration. Especially given the actual recipe for the Mystical World book requires one.

I'm happy if you want to adjust things yourself in your own pack, but I'm not happy with making it something that's baked-in by default -- I'd rather not have it so that people just futzing around with the configurations can make it impossible to progress.

If you want to edit the grass drops yourself externally, I believe there are a number of mods that allow it (potentially even CraftTweaker addons). I don't have them immediately to hand but they should be searchable.

**Comment by nickjackson-ff** [comment]
Disappointing, but I can respect your decision and reasoning. Almost half of the seeds I get from grass are aubergine seeds, which is obviously overkill. Thanks for taking the time to review the request.

**Comment by duely** [comment]
I'm not sure how that could possibly be happening. Currently, aubergine seeds are programmed to be inserted with a weight of 5; according to the comments for `addGrassSeed`:

```
     * Register a new seed to be dropped when breaking tall grass.
     * @param weight The relative probability of the seeds,
     *               where wheat seeds are 10.
```

This implies that only a quarter of the seeds you get would be aubergine seeds. If you are playing with other mods that alter the frequency of wheat seeds or modify seeds in general, it's possible that is what's contributing to the situation; it's also possibly just the *idea* that you're getting them more frequently -- it is random after all, which doesn't mean an even distribution.

If you're still intent on changing things, you can use [Seed Drop by EwyBoy](https://www.curseforge.com/minecraft/mc-mods/seed-drop) to adjust the rates at which things drop from grass. 

I will potentially look into making the rate being configurable (i.e., 1-10), but not to the point where it could be turned off.

Additionally, I will be moving the assorted seeds/toasted seeds assets & items from Roots into Mystical World as they make more sense for Mystical World. That will at least give them another purpose beyond throwing away.

**Comment by nickjackson-ff** [comment]
The cause may be undetermined (perhaps another mod reducing vanilla drops), but I am very grateful for your reply. Thank you for the tip on how to adjust it myself, and for the reconsideration.

I am happy to hear stuff like assorted seeds will have a new home as well. Hopefully we'll see new applications, given the flexibility of Mystical World.

Thanks again!

**Comment by NillerMedDild** [comment]
In 1.14.4 the drop rate of Aubergine Seeds is equal to that of Seeds - I've destroyed about 1500 grass to test it. I think that's a bit overkill, it'd really be nice if it was configurable :x

**Comment by duely** [comment]
Yeah, 1.14.4 is a different kettle of fish. I'll try to see about adjusting the weight of it, although that can definitely be done by adding a datapack that modifies the grass_inject loot table for Mystical World.

**Comment by NillerMedDild** [comment]
Ah alright, I'll just do that then, thanks! I'm still learning what can be done with datapacks :P

**Comment by duely** [comment]
I'll obviously fix it in the base as well, but for now you can edit it with the datapack (hopefully)
