### ISSUE TITLE
"Parsing error loading built-in advancement" when Amethyst is disabled.

### ISSUE THREAD

**Issue by katubug** [MysticMods/MysticalWorld#60]
Hello! In my logs there's this error: https://pastebin.com/TmRXwQj3

I'm assume it's because I have the Amethyst disabled? It's not a big deal in any case, but I wanted to report it in case it helps anything. :)

* **Minecraft version:** 1.12.2
* **Forge version:** forge-1.12.2-14.23.5.2838-universal
* **Modpack version** (links to current modlist): [1.7.2](http://enthusiasticraft.cf/modpack-update-1-7-2/#modlist)
* **Mod versions:** 1.4.4.

**Comment by duely** [comment]
Indeed, that can be safely ignored. I'll triple-check to see if the conditional-advancements feature merged into Forge will prevent this...

**Comment by duely** [comment]
Actually, I'm leaving this as-is. It's starting to become frustrating trying to make everything configurable; I'm happy for people to enable/disable ore as far as it fits with world generation, but a) this issue should be fixed with the removal of conditional registration, and b) it's... supposed to be the core emblem of the mod.

**Comment by katubug** [comment]
I completely understand. Sorry for the trouble! I appreciate your kindness and effort, and I apologize for being nitpicky.

You also raise a good point - I'll either leave this be or maybe I'll disable a different amethyst that's less integral to its originating mod. Thank you for the response <3

**Comment by duely** [comment]
No worries! It only occurred to be halfway through writing it that I would've fixed it with my previous change anyway :)
