### ISSUE TITLE
Config Doesn't Effect Items in JEI

### ISSUE THREAD

**Issue by SirChamomile** [MysticMods/MysticalWorld#61]
I'm trying to remove a good portion of the items from your mod, and when I chose for example to remove the metals (items, blocks, etc.) this doesn't affect anything visible in JEI.

**Comment by duely** [comment]
Yes, this is intentional. The items are no longer conditionally registered; they remain available in case pack makers wish to disable the defaults but still use the items in some way.

You can manually hide them using Hide Mode in JEI, or you can use CraftTweaker's JEI compatibility to completely hide it (i.e., players can't re-open Hide Mode and Unhide items). 

By choice & design, we're not specifically hiding disabled items for maximum flexibility.

**Comment by duely** [comment]
(Also conditional registration caused a *lot* of other issues and I'm glad it's gone.)
