### ISSUE TITLE
1.14.4 Either this mod or its library is stopping loot from generating in jungle and desert temples

### ISSUE THREAD

**Issue by mewzurui** [MysticMods/MysticalWorld#82]
1.14.4 Either this mod or its library is stopping loot from generating in jungle and desert temples. I removed both of these and found a new temple in the same world and it loaded the loot. Other loot tables such as shipwrecks and buried treasure seem fine. 
![loottableerror](https://user-images.githubusercontent.com/25018301/68077775-1165f500-fda0-11e9-9f0d-588cd73f956a.PNG)

**Comment by duely** [comment]
This issue is actually being caused by *another* mod that is altering the loot table, adding an additional pool but failing to name it. Then, when it comes time for us to add to the loot table, Forge goes through the list of pools and then crashes because the name of the previously-added pool is "null".

I'd recommend finding out what other mods add loot using the LootTable method that you have included in your pack.

The reason why removing our mod fixes the issue is because it means no other mods are adding a pool, meaning that the unnamed (null) loot pool doesn't get accessed and does not cause a crash.

**Comment by mewzurui** [comment]
"I'd recommend finding out what other mods add loot using the LootTable method that you have included in your pack." how do I go about doing this. 1 by 1 elimination to find out which is throwing a null will be excessively timely.

**Comment by duely** [comment]
If you could provide me with the actual log rather than just a screenshot, it should say at the top of the crash what other mods have subscribers for that event. Therefore your list should be relatively short. Unfortunately you've only given me part of the information.

If you'd like to upload the log file, please do so via https://gist.github.com

**Comment by mewzurui** [comment]
There wasn't a crash. the game was playing fine and just not generating loot for those specific loot tables. I flew around to about 4 temples and 3 jungle pyramids and 0 loot generated in the chests. So i went to the 'latest' log and looked through till i saw the error. then removed this mod and its lib (which i had just added to my mods folder. Checked again and everything was fine. 

After this I removed a mod (Lets call it george) added yours back and everything worked. i added back 'george' and removed another mod (sally) with yours still in and everything worked. Then i readded 'sally' and again everything worked. May be it was a one off thing. But the issue only came up after i added your stuff so I thought id report it to you just in case.

**Comment by mewzurui** [comment]
And nevermind that last part I got the error again. Here is the log:
https://gist.github.com/mewzurui/31c28166b2af6036d0b9fc2604436cc2

And here is a snippet
![snipp](https://user-images.githubusercontent.com/25018301/68086901-837d1f00-fe1e-11e9-83bd-e2fb3b7afa8b.PNG)

**Comment by duely** [comment]
So one of the other mods that is firing before us (ExplorerCraft, not BountifulBaubles (I know teh author) or Upgrade Aquatic (pretty sure htey fixed theirs), or Ores All Easy) is screwing things u p. I'd recommend filing an issue with them instead.

**Comment by duely** [comment]
As this issue is stale and is being caused by another of the listed mods, I'm closing the issue.
